/**
* @author Firat Esmer <firat.esmer@osf.digital>
* @date 10/04/2021
* @description Constant values class
*/
public class Constants {
    public static final String ACTIVE = 'Active';
    public static final String ACTIVATED = 'Activated';
    public static final String ALLOCATED = 'Allocated';
    public static final String AMERICAN_EXPRESS = 'American Express';
    public static final String AMOUNT_WITH_TAX = 'AmountWithTax';
    public static final String AMOUNT_WITHOUT_TAX = 'AmountWithoutTax';
    public static final String APPROVED = 'Approved';
    public static final String ASSIGNED = 'Assigned';
    public static final String CANCELED = 'Canceled';
    public static final String CANCELLED = 'Cancelled';
    public static final String CAPTURE = 'Capture';
    public static final String CLOSED = 'Closed';
    public static final String CREATED = 'Created';
    public static final String DELIVERED = 'Delivered';
    public static final String DELIVERY_CHARGE = 'Delivery Charge';
    public static final String DINERS_CLUB = 'Diners Club';
    public static final String DRAFT = 'Draft';
    public static final String ERROR_POSTING = 'Error Posting';
    public static final String ESTIMATED = 'Estimated';
    public static final String EXTERNAL = 'External';
    public static final String FAILED = 'Failed';
    public static final String FULFILLED = 'Fulfilled';
    public static final String FULFILLMENT = 'Fulfillment';
    public static final String GROSS = 'Gross';
    public static final String HTTP_REQUEST = 'HTTP request';
    public static final String HTTP_RESPONSE = 'HTTP response';
    public static final String ID = 'Id';
    public static final String IGNORED = 'Ignored';
    public static final String INACTIVE = 'Inactive';
    public static final String IN_STORE_PICKUP = 'In Store Pickup';
    public static final String INVOICING = 'Invoicing';
    public static final String JCB = 'JCB';
    public static final String MAESTRO = 'Maestro';
    public static final String MASTER_CARD = 'Master Card';
    public static final String NEW_C = 'New';
    public static final String ORDER_ACTIVATION = 'Order Activation';
    public static final String ORDER_APPROVAL = 'Order Approval';
    public static final String ORDER_PRODUCT = 'Order Product';
    public static final String ORDERED = 'Ordered';
    public static final String PAID = 'PAID';
    public static final String PARTIALLY_ALLOCATED = 'Partially Allocated';
    public static final String PARTIALLY_FULFILLED = 'Partially Fulfilled';
    public static final String PAYMENT = 'Payment';
    public static final String PENDING = 'Pending';
    public static final String PICKPACK = 'Pickpack';
    public static final String POST = 'POST';
    public static final String POSTED = 'Posted';
    public static final String PROCESSED = 'Processed';
    public static final String RESHIPPED = 'Reshipped';
    public static final String RESOLVED = 'Resolved';
    public static final String RETAIL_STORE = 'Retail Store';
    public static final String RETURNED = 'Returned';
    public static final String SALE = 'Sale';
    public static final String SHIPPED = 'Shipped';
    public static final String STORE = 'Store';
    public static final String SUBMITTED = 'Submitted';
    public static final String TEST = 'Test';
    public static final String UNKNOWN = 'Unknown';
    public static final String VIRTUAL_C = 'Virtual';
    public static final String VISA = 'Visa';
    public static final String WAITING_TO_FULFILL = 'Waiting to Fulfill';
    public static final String WAREHOUSE = 'Warehouse';

    public static final Integer HTTP_INTERNAL_ERROR_CODE = 500;
    public static final Integer HTTP_SUCCESS_CODE = 200;
}